name: shopping_app
description: Simple Flutter Shopping App

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/products.json
